#use_frameworks!

platform :ios, '9.0'

target 'GMBaseThirdSDK_Example' do
  pod 'GMBaseThirdSDK', :path => '../'

  target 'GMBaseThirdSDK_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
